
#
#
# BIN				- 可执行文件
# LIBA				- 静态库
# LIBSO				- 动态库
#
# PRODUCT 			- 产品名称
# VERSION			- 版本号
#
# DEPEND_LIBS		- 依赖的其他第三方库
# DEPEND_MODULES	- 依赖的项目的其他模块, LINK时必须手动添加/
#
#

BIN				= dbclient

PRODUCT 		= dbclient
VERSION			= 0.1.1

DEPEND_LIBS		= libdbclient.so

DEPEND_MODULES 	= $(ROOT)/src/utils

include $(ROOT)/Makefile.rules
